# Site settings
title: Blag
email: dannychen579@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://an.us" # the base hostname & protocol for your site
twitter_username: n/a
github_username:  SrsBusiness

# Build settings
markdown: kramdown
