# Site settings
title: 'CS373 Spring 2016: Danny Chen'
email: dannychen579@utexas.edu
description: 'Blog for CS373' # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
avatar: /images/avatar.png
url: http://srsbusiness.github.io # the base hostname & protocol for your site
twitter_username: n/a
github_username:  SrsBusiness

# Build settings
markdown: kramdown

